trigger: none  # No automatic trigger, only manual trigger

pool:
  vmImage: 'windows-2019'

variables:
  - group: secrets

stages:
  # Stage 1: Build
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: Build
        displayName: 'Build Application'
        steps:
          # Checkout the code
          - checkout: self  # Ensure the repository is checked out

          # Clean and compile the project with Maven
          - task: Maven@3
            displayName: 'Maven Clean and Compile'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean compile'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              mavenVersionOption: 'Default'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: false
              effectivePomSkip: false

  # Stage 2: Package
  - stage: Package
    displayName: 'Package Application'
    dependsOn: Build  # This ensures the Package stage runs after Build
    jobs:
      - job: Package
        displayName: 'Package Application'
        steps:
          # Package the application with Maven
          - task: Maven@3
            displayName: 'Maven Package'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              mavenVersionOption: 'Default'
              mavenOptions: '-DskipTests'
              mavenAuthenticateFeed: false
