trigger: none  # No automatic trigger, only manual trigger

pool:
  vmImage: 'windows-2019'

variables:
  - group: secrets

stages:
  - stage: Build
    displayName: 'Build and Package Application'
    jobs:
      - job: BuildAndPackage
        displayName: 'Build and Package Application'
        steps:
          # Checkout the code
          - checkout: self  # Ensure the repository is checked out

          # Clean, compile, and run Maven with detailed logs
          - task: Maven@3
            displayName: 'Maven Clean, Compile and Package'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean compile package'
              publishJUnitResults: false  # Do not publish separate JUnit results
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              mavenVersionOption: 'Default'
              mavenOptions: '-X -DskipTests'  # Enable debug and skip tests
              mavenAuthenticateFeed: false
              effectivePomSkip: false

  - stage: ZipAndPublishArtifacts
    displayName: 'Zip and Publish Artifacts'
    dependsOn: Build  # This stage depends on the Build stage
    jobs:
      - job: ZipAndPublish
        displayName: 'Zip and Publish Build Artifacts'
        steps:
          # Ensure the build output is available
          - checkout: self  # Ensure the repository is checked out

          # Zip the Maven build artifacts
          - task: PowerShell@2
            displayName: 'Zip Maven Artifacts'
            inputs:
              targetType: 'inline'
              script: |
                # Define the output path for the zip file
                $outputPath = "$(Build.ArtifactStagingDirectory)/maven_artifacts.zip"
                # Compress the target folder into a zip file
                Add-Type -AssemblyName System.IO.Compression.FileSystem
                [System.IO.Compression.ZipFile]::CreateFromDirectory("$(System.DefaultWorkingDirectory)/target", $outputPath)
                Write-Output "Artifacts zipped to $outputPath"

          # Publish the zipped artifacts
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Zipped Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/maven_artifacts.zip'
              ArtifactName: 'maven_artifacts'
              publishLocation: 'Container'
  - stage: CopyArtifactsAndBuildDockerImage
    displayName: 'Copy Artifacts and Build Docker Image'
    dependsOn: ZipAndPublishArtifacts
    jobs:
      - job: CopyAndBuildDocker
        displayName: 'Download Artifacts and Build Docker Image'
        pool:
          vmImage: 'ubuntu-latest'  # Use Linux-based VM for Docker tasks
        steps:
          # Download the artifacts from the previous stage
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: 'maven_artifacts'  # Name of the artifact published in the previous stage
              targetPath: '$(Pipeline.Workspace)/artifacts'  # Where to download the artifacts

          # List contents of artifact staging directory to verify downloaded files
          - script: |
              echo "Contents of $(Pipeline.Workspace)/artifacts:"
              ls -R $(Pipeline.Workspace)/artifacts
            displayName: 'List Artifact Directory Contents'

          # Build the Docker image using the downloaded artifacts
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              containerRegistry: 'DockerHub'
              repository: 'parkasssist/aspice'
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'
              tags: |
                $(Build.BuildId)
                latest
