trigger: none  # No automatic trigger, only manual trigger

pool:
  vmImage: 'windows-2019'

variables:
  - group: secrets

stages:
  - stage: Build
    displayName: 'Build and Package Application'
    jobs:
      - job: BuildAndPackage
        displayName: 'Build and Package Application'
        steps:
          # Checkout the code
          - checkout: self  # Ensure the repository is checked out

          # Clean, compile, and run Maven with detailed logs
          - task: Maven@3
            displayName: 'Maven Clean, Compile and Package'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean compile package'
              publishJUnitResults: false  # Do not publish separate JUnit results
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              mavenVersionOption: 'Default'
              mavenOptions: '-X -DskipTests'  # Enable debug and skip tests
              mavenAuthenticateFeed: false
              effectivePomSkip: false
